name: Next Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd /services/ecommerce-project/front-end
            git fetch origin
            git reset --hard origin/main
            docker build -t blog-starter .
            docker stop  || true
            docker rm  || true
            docker run -d -p 4000:3000 blog-starter
